#!/usr/bin/env bash
# Post-processes the private developer documentation generated by
# `dune build @doc-private`. It turns the index.mld page into the landing page
# of the internal library and copies the ./include assets it references.
#
# Usage: copy.sh <html-dir>
#   <html-dir> is a *writable* copy of dune's _doc/_html output (the Makefile
#   copies it to ocamldoc/ before calling this script). We do not write into
#   dune's _build tree because dune marks its build artifacts read-only.
set -euo pipefail

html_path="${1:?usage: copy.sh <html-dir>}"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
byte_objs="$script_dir/../../_build/default/src/.kind2dev.objs/byte"

# get name of internal library (dune names it kind2dev@<digest>)
lib_name=$(ls "$html_path" | grep kind2dev)

# copy ./include dir (referenced by index.mld) into the library documentation dir
cp -r "$script_dir/include" "$html_path/$lib_name"

# compile index.mld into a page-index.odoc file
tmp_odoc=$(mktemp -d)
trap 'rm -rf "$tmp_odoc"' EXIT
odoc compile --pkg="$lib_name" -o "$tmp_odoc/page-index.odoc" "$script_dir/index.mld"

# convert page-index.odoc to index.html and resolve links to other webpages.
# --theme-uri/--support-uri point the page's odoc.css and highlight.pack.js
# links at dune's support directory ($html_path/odoc.support); without them
# odoc emits its default paths ($html_path/odoc.css, ...) and the landing page
# ends up unstyled.
odoc html "$tmp_odoc/page-index.odoc" -I "$byte_objs" \
	--theme-uri odoc.support --support-uri odoc.support -o "$html_path"

# drop the kmoxi documentation: it is a separate package, not part of the
# kind2 developer documentation
rm -rf "$html_path/kmoxi"

# make the top-level index link to the internal library documentation, and
# remove the (now orphaned) kmoxi entry from the package list
sed -e "s/kind2/$lib_name/g" -e '/kmoxi/d' "$html_path/index.html" > "$html_path/index.html_tmp"
mv "$html_path/index.html_tmp" "$html_path/index.html"
