#!/usr/bin/env bash
# Post-processes the developer documentation generated by `dune build @doc-new`.
# It builds the landing page out of index.mld and copies the ./include assets
# that page references.
#
# Usage: copy.sh <html-dir>
#   <html-dir> is a *writable* copy of dune's _doc_new/html output (the Makefile
#   copies it to ocamldoc/ before calling this script). We do not write into
#   dune's _build tree because dune marks its build artifacts read-only.
set -euo pipefail

html_path="${1:?usage: copy.sh <html-dir>}"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
odoc_path="$script_dir/../../_build/default/_doc_new/odoc"

# get name of internal library (dune names it kind2dev@<digest>)
lib_name=$(ls "$html_path/docs" | grep kind2dev)

# copy ./include dir (referenced by index.mld) next to the page that uses it
cp -r "$script_dir/include" "$html_path/include"

# dune's odoc driver puts everything it generates under docs/, and every page
# it writes carries an "Index" breadcrumb pointing one level further up, at a
# root page dune itself does not produce. index.mld becomes that page: compiled
# as a root page rather than as part of the library, its {!modules:...}
# references come out as docs/<lib>/<Module>/index.html, so the landing page and
# the several hundred breadcrumbs both land where they should.
tmp_odoc=$(mktemp -d)
trap 'rm -rf "$tmp_odoc"' EXIT

odoc compile --output-dir "$tmp_odoc" --parent-id "" "$script_dir/index.mld"

# -L is what lets {!modules: Flags} and friends resolve against the library
# dune compiled, without naming it in every reference.
odoc link -L "$lib_name:$odoc_path/$lib_name" \
	-o "$tmp_odoc/page-index.odocl" "$tmp_odoc/page-index.odoc"

# --theme-uri/--support-uri point the page's odoc.css and highlight.pack.js
# links at dune's support directory ($html_path/docs/odoc.support); without them
# odoc emits its default paths ($html_path/odoc.css, ...) and the landing page
# ends up unstyled.
odoc html-generate --output-dir "$html_path" \
	--theme-uri docs/odoc.support --support-uri docs/odoc.support \
	"$tmp_odoc/page-index.odocl"
