#!/bin/sh

#########################################################################
# This file is part of the Kind 2 model checker.                        #
#                                                                       #
# Copyright (c) 2014 by the Board of Trustees of the University of Iowa #
#                                                                       #
# Licensed under the Apache License, Version 2.0 (the "License"); you   #
# may not use this file except in compliance with the License.  You     #
# may obtain a copy of the License at                                   #
#                                                                       #
# http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                       #
# Unless required by applicable law or agreed to in writing, software   #
# distributed under the License is distributed on an "AS IS" BASIS,     #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or       #
# implied. See the License for the specific language governing          #
# permissions and limitations under the License.                        #
#########################################################################


workdir="$HOME/kind2_continuous_doc_build"
cd $workdir

# update develop branch
git checkout develop
git pull

# make dev documentation
make kind2-doc

# copy new documentation to remote web server
scp -r -i ~/.ssh/id_rsa_copy_ocamldoc ocamldoc/* kind.cs.uiowa.edu:.

exit 0
