
name: Kind2-MCIL CI

on:
  pull_request:
    branches: [ mcil ]
  push:
    branches: [ mcil ]

jobs:
  kind2-linux-bin:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build and push to local registry
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile
        context: ./
        target: builder
        push: true
        tags: localhost:5000/name/kind2:latest
    
    - name: Extract kind2-mcil binary
      id: extract
      uses: shrink/actions-docker-extract@v1
      with:
        image: localhost:5000/name/kind2:latest
        path: /home/opam/kind2-build/bin/kind2-mcil

    - name: Upload kind2-mcil binary
      uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: kind2-mcil-linux


  kind2-macos-bin:
    strategy:
      matrix: # Single configuration
        ocaml-version: [ 4.14.0 ]
        # Only matrix variables can be used at runs-on
        os: [ macos-11 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up OCaml ${{ matrix.ocaml-version }}+flambda
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ocaml-variants.${{ matrix.ocaml-version }}+options,ocaml-option-flambda

    - name: Pin MCIL version of Dolmen packages
      run: |
        opam pin -y add dolmen https://github.com/ModelChecker/dolmen.git#mcil
        opam pin -y add dolmen_type https://github.com/ModelChecker/dolmen.git#mcil
        opam pin -y add dolmen_loop https://github.com/ModelChecker/dolmen.git#mcil

    - name: Install Kind2 OCaml dependencies
      run: opam install -y . --deps-only

    - name: Build Kind 2
      run: opam exec make static

    - name: Strip binary
      run: strip bin/kind2-mcil

    - name: Upload kind2-mcil artifact
      uses: actions/upload-artifact@v3
      with:
        name: kind2-mcil-${{ matrix.os }}
        path: bin/kind2-mcil
